name: Build VALORANT Karmalocker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Replace bottle.py
      run: python install_and_build/replace_bottle.py

    - name: Build application
      run: |
        python -m eel main.py web --onefile --noconsole --icon=./web/favicon.ico --name="VALORANT Karmalocker" --paths ./venv/Lib/site-packages

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ./dist